### ISSUE TITLE
onReceivedSslError in Android (Xamarin Forms)

### ISSUE THREAD

**Issue by atkinsonline** [SKLn-Rad/Xam.Plugin.Webview#33]
Hi I've written a little app to wrap a web site and its working fine to the live web site but when it tries to browse to a development web site on a development server, it gets a certificate error

I/X509Util(32515): Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

I can't quite explain this as the certificate appears to be the same and hence should be installed on the device.  As this is only a dev version of the app connecting to a dev server on an intranet, I'm not bothered about ignoring all certificate errors.  The problem is, I can't get the event to fire to show a certificate error has occurred.   I've seen from a web site post elsewhere that I need something like this:

```
public override void onReceivedSslError(WebView view, SslErrorHandler handler, SslError er)
        {
            handler.proceed();
            // Ignore SSL certificate errors
        }
```
The problem is, I don't know where to put the above code. I tried in WebView.Plugin.Shared FormsWebViewRenderer.cs (it does compile in there) but the above event never fires.  I set a break point and it is not hit and I still get the certificate error shown in the debugger.
I tried placing it in other similar modules (eg WebView.Plugin.Droid FormsWebViewRenderer.cs and FormsWebViewClient.cs but I get compilation errors in those. EG No sensible method found to override.

Do you know where this override should go?

Thank you
John.

**Comment by SKLn-Rad** [comment]
Hey John, sorry about the extremally slow response. I've been so busy as of late with moving house amongst other things.
The handler should be overriden in the WebViewClient which I set up here:
https://github.com/SKLn-Rad/Xam.Plugin.Webview/blob/master/WebViewPlugin/WebView.Plugin.Droid/Extras/FormsWebViewClient.cs

The issue is, I don't think you can override it without removing my webview client in the process. I think the best way around this would be for me to expose an event in the Android Renderer allowing you to toggle ignoring SSL errors and then override it myself in the client. How does that sound?

Question I would have is whether to make it static in the renderer (hence applying to all webviews), or to put it in the FormsWebView object and add a note that the method is only applicable for Android.

Let me know your thoughts, and next time if I am slow to reply, feel free to pop me a message on just about any other medium. Hopefully I should be a bit more active now!

Regards,
Ryan

**Comment by atkinsonline** [comment]
Hi Ryan,

No worries at all about the delay.  You provide fantastic support and go
above and beyond what anyone could expect.

I have no strong preference either way and you clearly have a lot more
knowledge than me on WebView. Anything you can provide when you get time
would be great.

Regards
John.

**Comment by SKLn-Rad** [comment]
Hey John
I was hoping to push this out with the port to netstandard and MacOS support. I can do another incremental build sooner (Like tonight) if you need this asap? Do let me know.

Regards,
Ryan

**Comment by atkinsonline** [comment]
Hi Ryan,

You really are brilliant!  I nearly asked if you'd had any time for it the other day but I really didn't want to do that so managed to resist. As it happens, there's been a delay in the project so please don't stress yourself with it. But it would be great when you get time.

Regards
John.

**Comment by SKLn-Rad** [comment]
I did a pre-release for 1.7.0 to fix some apple issues and added your feature in, you will have to enable pre-releases until I do an official release, but you can test it now at least!

1.7.0-rc1 👍

**Comment by atkinsonline** [comment]
Hi Ryan,

Sorry for the delay.  I'm on holiday at present so I won't be able to look
at this until later this week.

Regards

John.

**Comment by SKLn-Rad** [comment]
Closing as no response. However I did add this feature in 2.0.0.
Check out the docs if you need an example.
