### ISSUE TITLE
mac OSX

### ISSUE THREAD

**Issue by joeblew99** [SKLn-Rad/Xam.Plugin.Webview#35]
Does this support mac OSX ?

If you go the the last sentence on this page you can see they dont fully support Mac OSX.
https://developer.xamarin.com/guides/xamarin-forms/platform-features/mac/

**Comment by SKLn-Rad** [comment]
Not yet! I am planning to do a full official release with the next stable version of forms alongside a port to net standard. But since MacOS is only available for beta at the moment "As far as I am aware", I didn't want to commit to anything if the API's drastically change during launch.

Did you want me to keep the ticket open to track this or did that answer your question?

**Comment by joeblew99** [comment]
sorry its me again:) I raised the other tick. Super stupid of me.. 
Will close this one...
