### ISSUE TITLE
Events Such as OnScrolDown or ScrolUp

### ISSUE THREAD

**Issue by Doughouzlight** [SKLn-Rad/Xam.Plugin.Webview#39]
Hi Ryan,

I hope you are fine 

i am using your plugin from it first version and it seems every time it better than before 

i would ask for a request such as scroll events on web view so I can trigger events when user i scrolling down or up 

Thank you 

Regards 

Elin Doughouz

**Comment by SKLn-Rad** [comment]
Hey man, I have indeed been looking into this. Problem is the lack of support by Microsoft for the UWP Webview! :( Currently there is no way to detect scroll events in this control.

Albeit you could get around it with javascript, which is probably the best solution. for example: window.onScroll.

If you find a way to get this working on Windows then do let me know and I would be happy to support it. I don't however want to start injecting my own Javascript in order to monitor events like this if avoidable.

Let me know your thoughts 👍

**Comment by SKLn-Rad** [comment]
Closing as this is not exposed on the required webviews and instead is generally handled inside javascript.
