### ISSUE TITLE
InjectJavascriptAsync working on android, but not on UWP

### ISSUE THREAD

**Issue by danieljaguiar** [SKLn-Rad/Xam.Plugin.Webview#49]
Here is a very simple example:

```
fwebView.ContentType = Xam.Plugin.WebView.Abstractions.Enumerations.WebViewContentType.StringData;
fwebView.Source = @"<html>
  <body>
	<div id='player'></div>

	<script>
	  var tag = document.createElement('script');

	  tag.src = 'https://www.youtube.com/iframe_api';
	  var firstScriptTag = document.getElementsByTagName('script')[0];
	  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

	  var player;
	  function onYouTubeIframeAPIReady() {
		player = new YT.Player('player', {
		  height: '390',
		  width: '640',
		  videoId: 'M7lc1UVf-VE',
		  events: {
			'onReady': onPlayerReady,
		  }
		});
	  }

	  function onPlayerReady(event) {
		event.target.playVideo();
	  }

	function myStop() {
		player.stopVideo();
		return 'x'; 
	  }
	</script>
  </body>
</html>";
```
Then you try to call

`fwebView.InjectJavascriptAsync("myStop()");`

It works on Android, but not on UWP. (no error though)

**Comment by danieljaguiar** [comment]
BY the way, I updated it to 2.0.7 and got same error... 

Isn't it related to [isJavaScriptEnabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewsettings#Windows_UI_Xaml_Controls_WebViewSettings_IsJavaScriptEnabled) ?

**Comment by SKLn-Rad** [comment]
Hey man, sorry for the delay.
Having a look at this, it appears that the problem is down to the 'Edge Engine', running the web view for UWP.

If you enable Script debugging in the UWP project, you will see when you call stopVideo, its complaining that the player object does not have a method for stopVideo. If you look even closer, you will notice that the OnReady event is not even firing for UWP.

I tried running this directly in Edge rather than using my method, replacing the Inject for an actual button event and got exactly the same problem. I expect you could get around it by using the old school embedded iframe technique with jsapi.isenabled, but I would have to look more into it.

I don't mind having a more detailed look if you want, but I don't think the problem is with my abstraction of the webview, rather the webview itself... Edge === IE in short 👎 

What are your thoughts? And once again, apologies for the delay!

**Comment by danieljaguiar** [comment]
OK... having android working fine will do it!!! thanks a lot
