### ISSUE TITLE
Feature Request: ContentFinishedLoading() Event

### ISSUE THREAD

**Issue by acicovic** [SKLn-Rad/Xam.Plugin.Webview#7]
Hi, I hope that all is well!

Once my WebView has finished loading its contents, I need to execute a C# function which in turn calls InjectJavascript() with specific arguments. This must be done at that point in time to modify content within the WebView. I did not find a function/event for that (If I'm not mistaken, the XForms equivalent is the LoadFinished() event).

In my case I could probably initiate this from javascript when everything has been loaded (JS to C# and then C# back to JS) but still, this would be a useful feature to have if it's not difficult to implement.

Thanks!

**Comment by acicovic** [comment]
At the moment, the only way to do this reliably seems to be the WebView's NavigationCompleted event. Calls to Callbacks or the csharp function from JS events (vanilla or with jQuery) fail.

Sample code [here](https://github.com/acicovic/FormsWebViewTests)

**Comment by SKLn-Rad** [comment]
Hey man, sorry for the slow response. Been busy as always with full time work!
Give 1.3.0 a go! I hooked into the native components OnContentLoaded events so this should do what you want.

There are a lot of changes to improve the quality of life for people who are coming from XForms and Native so please let me know if you have any problems. You WILL need to execute all of your Javascript from this event instead of the OnNavigationComplete as you would of done previously.

Also, there should be some fixes for https://github.com/SKLn-Rad/Xam.Plugin.Webview/issues/4 in there as well. You can now remove the prefixing file:// and use the BaseUrl in the renderers if you want to change the location from the defaults.

- Ryan

**Comment by acicovic** [comment]
Hi Ryan,

Thank you for all your work. I've been migrating from XForms to your WebView in my main application. I will give it a go and let you know!

**Comment by acicovic** [comment]
OnContentLoaded works for me on Android and iOS.
